<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>YarrOverlay</AssemblyName>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishSelfContained>true</PublishSelfContained>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugSymbols>false</DebugSymbols>
    <DebugType>None</DebugType>
    <PublishDir>$(MSBuildProjectDirectory)\bin\Release\single-file\</PublishDir>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Hexa.NET.ImGui.Backends" Version="1.0.18" />
    <PackageReference Include="TerraFX.Interop.Windows" Version="10.0.26100.6" />
    <PackageReference Include="Vortice.D3DCompiler" Version="3.8.3" />
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
    <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
    <PackageReference Include="Vortice.DirectComposition" Version="3.8.3" />
  </ItemGroup>
</Project>
